CREATE DATABASE IF NOT EXISTS `sr` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `sr`;

CREATE TABLE IF NOT EXISTS `rcbz_code_dtl_info` (
    `CD_ID` VARCHAR(6) NOT NULL,
    `DTL_CD_ID` VARCHAR(100) NOT NULL,
    `DTL_CD_NM` VARCHAR(100) NOT NULL DEFAULT ' ',
    `RGR_ENO` VARCHAR(13) NOT NULL DEFAULT ' ',
    `RG_DT` VARCHAR(8) NOT NULL DEFAULT ' ',
    `DLR_ENO` VARCHAR(13) NOT NULL DEFAULT ' ',
    `DL_DT` VARCHAR(8) NOT NULL DEFAULT ' ',
    PRIMARY KEY (`CD_ID`, `DTL_CD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `srmg_emp_rgh` (
    `RGH_ID` VARCHAR(4) NOT NULL,
    `RHG_NM` VARCHAR(100) NOT NULL DEFAULT ' ',
    `VL_YN` VARCHAR(1) NOT NULL DEFAULT ' ',
    `SYS_FST_RG_TS` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `SYS_FST_RG_USID` VARCHAR(50) NOT NULL DEFAULT ' ',
    `SYS_LT_CH_TS` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `SYS_LT_CH_USID` VARCHAR(50) NOT NULL DEFAULT ' ',
    PRIMARY KEY (`RGH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `srmg_emp_rle` (
    `RLE_ID` VARCHAR(4) NOT NULL,
    `RGH_ID` VARCHAR(4) NOT NULL,
    `APY_STRTDT` VARCHAR(8) NOT NULL,
    `APY_ENDDT` VARCHAR(8) NOT NULL DEFAULT ' ',
    `RLE_NM` VARCHAR(100) NOT NULL DEFAULT ' ',
    `SYS_FST_RG_TS` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `SYS_FST_RG_USID` VARCHAR(50) NOT NULL DEFAULT ' ',
    `SYS_LT_CH_TS` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `SYS_LT_CH_USID` VARCHAR(50) NOT NULL DEFAULT ' ',
    PRIMARY KEY (`RLE_ID`, `RGH_ID`, `APY_STRTDT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `srmg_emp_rle_rgh_bas` (
    `EMPNO` VARCHAR(13) NOT NULL,
    `DV_C` VARCHAR(1) NOT NULL,
    `RLE_RGH_ID` VARCHAR(4) NOT NULL,
    `APY_STRTDT` VARCHAR(8) NOT NULL,
    `APY_ENDDT` VARCHAR(8) NOT NULL DEFAULT ' ',
    `SYS_FST_RG_TS` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `SYS_FST_RG_USID` VARCHAR(50) NOT NULL DEFAULT ' ',
    `SYS_LT_CH_TS` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `SYS_LT_CH_USID` VARCHAR(50) NOT NULL DEFAULT ' ',
    PRIMARY KEY (`EMPNO`, `DV_C`,`RLE_RGH_ID`, `APY_STRTDT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `srmg_login_inf` (
    `EMPNO` VARCHAR(13) NOT NULL,
    `PW` VARCHAR(22) NOT NULL DEFAULT ' ',
    `SYS_FST_RG_TS` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `SYS_FST_RG_USID` VARCHAR(50) NOT NULL DEFAULT ' ',
    `SYS_LT_CH_TS` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `SYS_LT_CH_USID` VARCHAR(50) NOT NULL DEFAULT ' ',
    PRIMARY KEY (`EMPNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `sr_dev_emp_bas` (
    `EMPNO` VARCHAR(13) NOT NULL,
    `FNM` VARCHAR(22) NOT NULL DEFAULT ' ',
    `GRP` VARCHAR(1) NOT NULL DEFAULT ' ',
    `MNGR_RGH_YN` VARCHAR(1) NOT NULL DEFAULT ' ',
    `DL_YN` VARCHAR(1) NOT NULL DEFAULT ' ',
    PRIMARY KEY (`EMPNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;